{"@t":"2022-02-09T13:21:22.8049429Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"test question","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":20,"HttpRequestId":"21b12dbf-6467-4cc3-8178-8a37a7e97c67"}
{"@t":"2022-02-09T13:22:41.6450502Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":58,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":21,"HttpRequestId":"3c5fd142-cb0d-45a8-9e18-d3d1160f1dff"}
{"@t":"2022-02-09T13:22:41.6729790Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":58,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":21,"HttpRequestId":"3c5fd142-cb0d-45a8-9e18-d3d1160f1dff"}
{"@t":"2022-02-09T13:23:07.2774976Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"test question","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":47,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":22,"HttpRequestId":"fbc21d26-909a-4ab4-90d9-f4bd099c92b1"}
{"@t":"2022-02-09T13:23:09.7493726Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:25:46.2519960Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":23,"HttpRequestId":"132aa16c-fd74-4c5c-9489-6911561337f1"}
{"@t":"2022-02-09T13:25:46.2739377Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":23,"HttpRequestId":"132aa16c-fd74-4c5c-9489-6911561337f1"}
{"@t":"2022-02-09T13:25:48.6110774Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":82,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:26:45.4407103Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":24,"HttpRequestId":"ce85c4b7-6810-487a-b56e-576b58257233"}
{"@t":"2022-02-09T13:26:45.4666467Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":24,"HttpRequestId":"ce85c4b7-6810-487a-b56e-576b58257233"}
{"@t":"2022-02-09T13:26:53.5470010Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":25,"HttpRequestId":"2d99a8c9-6d97-41c7-aedb-4552bd427c3c"}
{"@t":"2022-02-09T13:26:53.5978689Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":25,"HttpRequestId":"2d99a8c9-6d97-41c7-aedb-4552bd427c3c"}
{"@t":"2022-02-09T13:26:55.9142711Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":85,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:28:08.6199200Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":88,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":26,"HttpRequestId":"aa796406-bf7c-4f0c-b997-9319ed87ddfb"}
{"@t":"2022-02-09T13:28:08.6677908Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":88,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":26,"HttpRequestId":"aa796406-bf7c-4f0c-b997-9319ed87ddfb"}
{"@t":"2022-02-09T13:28:27.5370941Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":27,"HttpRequestId":"e551ab08-0e00-46fa-b5ec-e5928de0520b"}
{"@t":"2022-02-09T13:28:27.5530547Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":27,"HttpRequestId":"e551ab08-0e00-46fa-b5ec-e5928de0520b"}
{"@t":"2022-02-09T13:28:29.8595254Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":55,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:28:40.0220713Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"test question","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":28,"HttpRequestId":"9bd465b5-4b85-41ff-8a74-11ce7d0b88c9"}
{"@t":"2022-02-09T13:28:42.4672779Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":55,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:29:12.8112616Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"What second space mission was Neil Armstrong part of?","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":29,"HttpRequestId":"0c8080b7-2015-495c-94bf-f6a5549d9f1e"}
{"@t":"2022-02-09T13:29:15.2864073Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:31:31.7442016Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":30,"HttpRequestId":"1ac22b50-c22c-4dfe-a2ab-c2b322fff944"}
{"@t":"2022-02-09T13:31:31.7621565Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":30,"HttpRequestId":"1ac22b50-c22c-4dfe-a2ab-c2b322fff944"}
{"@t":"2022-02-09T13:31:35.7156043Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":76,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":31,"HttpRequestId":"46ebc384-b340-43dc-907d-1c2975956af5"}
{"@t":"2022-02-09T13:31:35.7465245Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":76,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":31,"HttpRequestId":"46ebc384-b340-43dc-907d-1c2975956af5"}
{"@t":"2022-02-09T13:31:38.0480018Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":91,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:31:40.8678588Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":93,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":32,"HttpRequestId":"a572d624-c0e6-42ef-b7ea-0a66e37ebcd3"}
{"@t":"2022-02-09T13:31:40.9007735Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":93,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":32,"HttpRequestId":"a572d624-c0e6-42ef-b7ea-0a66e37ebcd3"}
{"@t":"2022-02-09T13:31:54.6910269Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"What second space mission was Neil Armstrong part of?","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":33,"HttpRequestId":"b1e14619-233b-479d-a52e-28924e732804"}
{"@t":"2022-02-09T13:31:57.1506730Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":90,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:32:20.4855195Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"What second space mission was Neil Armstrong part of?","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":34,"HttpRequestId":"c1d6abfb-c627-40d5-9f12-2912421abf01"}
{"@t":"2022-02-09T13:32:22.8816075Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":90,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:35:35.6824614Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":82,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":35,"HttpRequestId":"bd897457-12ac-4657-b401-58f248f6e1d2"}
{"@t":"2022-02-09T13:35:35.7203509Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":82,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":35,"HttpRequestId":"bd897457-12ac-4657-b401-58f248f6e1d2"}
{"@t":"2022-02-09T13:35:38.0300829Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":99,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:36:34.2030562Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":36,"HttpRequestId":"b12f252a-1c59-4877-93df-2329bb6c4e04"}
{"@t":"2022-02-09T13:36:34.2329782Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":36,"HttpRequestId":"b12f252a-1c59-4877-93df-2329bb6c4e04"}
{"@t":"2022-02-09T13:36:36.5954388Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":99,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:36:36.9208348Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":98,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:40:22.8835751Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":98,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":37,"HttpRequestId":"b6caf014-ddcd-4b77-bc56-c8c713643b3d"}
{"@t":"2022-02-09T13:40:22.9124960Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":98,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":37,"HttpRequestId":"b6caf014-ddcd-4b77-bc56-c8c713643b3d"}
{"@t":"2022-02-09T13:40:25.1968114Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:40:33.9800763Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"What second space mission was Neil Armstrong part of?","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":93,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":38,"HttpRequestId":"51d4dfbc-c326-4a3b-82ad-27fd1c3a0fe8"}
{"@t":"2022-02-09T13:40:36.4545095Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:41:09.4165706Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"What second space mission was Neil Armstrong part of?","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":39,"HttpRequestId":"c6a5ea2a-2bd2-469b-bf0d-9a913a142a1d"}
{"@t":"2022-02-09T13:41:11.9840635Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:41:44.3237318Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"What second space mission was Neil Armstrong part of?","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":97,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":40,"HttpRequestId":"5907f031-c508-4015-b09c-7f1d2faa3c25"}
{"@t":"2022-02-09T13:41:46.7666576Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:41:49.9407854Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":100,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":41,"HttpRequestId":"27754609-9b62-4a64-b0ba-30e4a9aa2952"}
{"@t":"2022-02-09T13:41:49.9637293Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":100,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":41,"HttpRequestId":"27754609-9b62-4a64-b0ba-30e4a9aa2952"}
{"@t":"2022-02-09T13:41:52.2873514Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:50:33.4638791Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"What second space mission was Neil Armstrong part of?","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":76,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":42,"HttpRequestId":"7d6d140f-3d12-455c-921d-74f567d6fc54"}
{"@t":"2022-02-09T13:50:35.8861897Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:53:36.3502726Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":43,"HttpRequestId":"cc32796d-8376-4c61-a1c7-2bda24b9fd06"}
{"@t":"2022-02-09T13:53:36.3891693Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":43,"HttpRequestId":"cc32796d-8376-4c61-a1c7-2bda24b9fd06"}
{"@t":"2022-02-09T13:53:38.6854731Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":91,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:55:29.5180349Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"who was the first astronaut?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":95,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":44,"HttpRequestId":"decb0371-885a-46be-84cb-1106d6b9878d"}
{"@t":"2022-02-09T13:55:33.1674188Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:57:23.8341940Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":95,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":45,"HttpRequestId":"755367ca-ed5c-40fb-92ef-fcbff995cb26"}
{"@t":"2022-02-09T13:57:23.8896768Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":95,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":45,"HttpRequestId":"755367ca-ed5c-40fb-92ef-fcbff995cb26"}
{"@t":"2022-02-09T13:57:26.2284574Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:57:26.5580255Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":62,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:58:15.9275273Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":95,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":46,"HttpRequestId":"d342fd4f-4618-495a-9fcb-2a49d2b6325f"}
{"@t":"2022-02-09T13:58:15.9664236Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":95,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":46,"HttpRequestId":"d342fd4f-4618-495a-9fcb-2a49d2b6325f"}
{"@t":"2022-02-09T13:58:18.2398606Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:58:20.9270525Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":57,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":47,"HttpRequestId":"0f876fe8-27d0-4c10-82c8-6d8f9e120ec8"}
{"@t":"2022-02-09T13:58:20.9609292Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":57,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":47,"HttpRequestId":"0f876fe8-27d0-4c10-82c8-6d8f9e120ec8"}
{"@t":"2022-02-09T13:58:23.3804022Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:58:45.9831186Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:59:32.3925798Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":83,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":48,"HttpRequestId":"6b44f41d-e8ab-4534-97a6-55670f0f431c"}
{"@t":"2022-02-09T13:59:32.4404516Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":83,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":48,"HttpRequestId":"6b44f41d-e8ab-4534-97a6-55670f0f431c"}
{"@t":"2022-02-09T13:59:34.8016202Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T13:59:57.2698700Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":49,"HttpRequestId":"08e6613a-d89d-4637-a332-8fe4dbe3b2a0"}
{"@t":"2022-02-09T13:59:57.3017929Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":49,"HttpRequestId":"08e6613a-d89d-4637-a332-8fe4dbe3b2a0"}
{"@t":"2022-02-09T13:59:59.6271818Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:00:58.9443669Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":50,"HttpRequestId":"43299f4f-e864-4410-86aa-9f7d84c4ffee"}
{"@t":"2022-02-09T14:00:58.9852568Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":50,"HttpRequestId":"43299f4f-e864-4410-86aa-9f7d84c4ffee"}
{"@t":"2022-02-09T14:01:05.7451064Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":51,"HttpRequestId":"3d81d25f-0a9f-4e71-b848-2188f62dd642"}
{"@t":"2022-02-09T14:01:05.7830099Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":51,"HttpRequestId":"3d81d25f-0a9f-4e71-b848-2188f62dd642"}
{"@t":"2022-02-09T14:01:08.0965563Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:01:23.5263236Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":52,"HttpRequestId":"df70de7a-e16e-4afc-b1b1-f275e5c0d555"}
{"@t":"2022-02-09T14:01:23.5412872Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":52,"HttpRequestId":"df70de7a-e16e-4afc-b1b1-f275e5c0d555"}
{"@t":"2022-02-09T14:01:25.8982410Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":62,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:01:38.5729533Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"what second space mission was Neil Armstrong part of?","ContentId":1131,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":53,"HttpRequestId":"8d1e940e-1087-4944-bd82-18123e3e56b1"}
{"@t":"2022-02-09T14:01:40.9753038Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":62,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:02:42.7842959Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"the first American astronauts insisted on the installation of an extra element to their spacecraft. What was it?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":83,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":54,"HttpRequestId":"d68b06a4-edd6-4ee3-9cdf-f049a1500003"}
{"@t":"2022-02-09T14:02:45.2781011Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":69,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:02:45.6076654Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:03:00.9595538Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"the first American astronauts insisted on the installation of an extra element to their spacecraft. What was it?","ContentId":1134,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":83,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":55,"HttpRequestId":"3a6cda4f-f3fc-4448-990d-c78c2c7b58e3"}
{"@t":"2022-02-09T14:03:03.3782822Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":69,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:04:08.2160751Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"who holds the record for the longest single stay of 14 months in space?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":58,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":56,"HttpRequestId":"784c727f-4e18-4c85-908f-c3fa593c9e65"}
{"@t":"2022-02-09T14:04:10.6707899Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:05:00.8591628Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"who was the first man to leave the spacecraft in space?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":61,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":57,"HttpRequestId":"66b5103c-1194-45cb-848e-858e4b7f2edb"}
{"@t":"2022-02-09T14:05:03.3012800Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":52,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:05:11.0090668Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"Astronauts","ContentId":1130,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":54,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":58,"HttpRequestId":"722a5f3b-fb62-4f78-a520-6bda0be129c1"}
{"@t":"2022-02-09T14:05:13.4676205Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:06:17.5736408Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":54,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":59,"HttpRequestId":"3ae11579-88a9-4bf9-bdf6-401612fee5f3"}
{"@t":"2022-02-09T14:06:17.6294918Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":54,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":59,"HttpRequestId":"3ae11579-88a9-4bf9-bdf6-401612fee5f3"}
{"@t":"2022-02-09T14:07:12.2997247Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":68,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":60,"HttpRequestId":"281217f7-04a0-4a3e-bbfa-16d0e1a997cf"}
{"@t":"2022-02-09T14:07:12.3485955Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":68,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":60,"HttpRequestId":"281217f7-04a0-4a3e-bbfa-16d0e1a997cf"}
{"@t":"2022-02-09T14:07:15.1656904Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":61,"HttpRequestId":"3f097707-d919-4d8c-9460-fe7ab200727d"}
{"@t":"2022-02-09T14:07:15.2644269Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":61,"HttpRequestId":"3f097707-d919-4d8c-9460-fe7ab200727d"}
{"@t":"2022-02-09T14:07:17.5398206Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:07:27.5837535Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:07:51.8427643Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":40,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":62,"HttpRequestId":"e8902c2c-04fb-4c2b-ae5a-977ed2939f3a"}
{"@t":"2022-02-09T14:07:51.8986139Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":40,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":62,"HttpRequestId":"e8902c2c-04fb-4c2b-ae5a-977ed2939f3a"}
{"@t":"2022-02-09T14:08:27.8708614Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:09:28.1408285Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:09:32.6952540Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"what is a meteorological satellite?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":40,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":63,"HttpRequestId":"49b3922b-6027-4b82-9d35-bf08e84a37be"}
{"@t":"2022-02-09T14:09:35.1434974Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":64,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:09:35.4843555Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:10:08.2320030Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:10:33.4003633Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:10:58.9787678Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"how do satellites stay in orbit around the earth?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":64,"HttpRequestId":"e732230c-79bd-425b-a436-a93c071f335a"}
{"@t":"2022-02-09T14:11:01.4089623Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:11:03.5131911Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:11:58.7569080Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:12:08.3832406Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"what is a satellite?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":65,"HttpRequestId":"0197dcd4-76a3-471a-bc44-6878b39a9760"}
{"@t":"2022-02-09T14:12:12.4686238Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":41,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:12:18.8145529Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":28,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:12:33.2953948Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"how many times does the ISS orbit around the earth in 24 hours?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":66,"HttpRequestId":"dc0a6695-75ca-4d50-9deb-6ff0c21a2cfd"}
{"@t":"2022-02-09T14:12:35.7277603Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:13:09.8843137Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"many planets have natural satellites which are known as what?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":67,"HttpRequestId":"05526497-5d19-4670-ada0-6349148062e8"}
{"@t":"2022-02-09T14:13:12.3532912Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":52,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:13:12.6963811Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:13:41.0853002Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"what is the largest planet in our solar system?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":68,"HttpRequestId":"87cc0587-9a94-49d8-9166-cfc4528df421"}
{"@t":"2022-02-09T14:13:43.5334771Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":28,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:14:23.5858833Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"what is the Earth's age?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":69,"HttpRequestId":"c188f7ad-7c6a-4c9f-af80-1d1a3cc24899"}
{"@t":"2022-02-09T14:14:26.0077152Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:16:29.0749749Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"how far away is venus?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":70,"HttpRequestId":"ea0ecc43-061a-4c57-b0b5-474b50afdcf1"}
{"@t":"2022-02-09T14:16:31.5521325Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":21,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:17:01.1368833Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"what is the smallest planet in our solar system","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":71,"HttpRequestId":"a9c73596-64c0-4339-a083-c2a8e8d80f2f"}
{"@t":"2022-02-09T14:17:03.5804438Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":9,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:17:42.3732390Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"which planet has the most moons?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":48,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":72,"HttpRequestId":"1caf8a5e-39fe-478c-912b-ce2df75cc7aa"}
{"@t":"2022-02-09T14:17:44.9071324Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":29,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:18:48.5852774Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"when was the last apollo mission?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":73,"HttpRequestId":"2935b9ed-1727-4faa-91e7-9ab794051de6"}
{"@t":"2022-02-09T14:18:51.0414634Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":44,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:19:24.2408194Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"what year did the USA land on the moon?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":74,"HttpRequestId":"13afd2dd-f21f-436f-9145-1c317dda1ea3"}
{"@t":"2022-02-09T14:19:26.7276979Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":44,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:23:08.6476801Z","@mt":"Unhandled controller exception occurred for request '{RequestUrl}'","@l":"Error","@x":"System.AggregateException: Exceptions were thrown by listed actions. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at Lucene.Net.Store.SimpleFSDirectory.OpenInput(String name, Int32 bufferSize) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Store\\SimpleFSDirectory.cs:line 72\r\n   at Lucene.Net.Index.FieldsReader..ctor(Directory d, String segment, FieldInfos fn, Int32 readBufferSize, Int32 docStoreOffset, Int32 size) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\FieldsReader.cs:line 106\r\n   at Lucene.Net.Index.SegmentReader.CoreReaders.OpenDocStores(SegmentInfo si) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\SegmentReader.cs:line 356\r\n   at Lucene.Net.Index.IndexWriter.ReaderPool.Get(SegmentInfo info, Boolean doOpenStores, Int32 readBufferSize, Int32 termsIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 702\r\n   at Lucene.Net.Index.IndexWriter.ReaderPool.GetReadOnlyClone(SegmentInfo info, Boolean doOpenStores, Int32 termInfosIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 630\r\n   at Lucene.Net.Index.DirectoryReader..ctor(IndexWriter writer, SegmentInfos infos, Int32 termInfosIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\DirectoryReader.cs:line 204\r\n   at Lucene.Net.Index.IndexWriter.GetReader(Int32 termInfosIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 392\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.ReaderReopener.MaybeReopen() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 463\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.ReaderReopener.ScheduleReopen() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 291\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.ValidateSearcher() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 222\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.GetLuceneSearcher() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 80\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.GetSearchContext() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 89\r\n   at Examine.LuceneEngine.Providers.BaseLuceneSearcher.CreateQuery(String category, BooleanOperation defaultOperation, Analyzer luceneAnalyzer, LuceneSearchOptions searchOptions) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\BaseLuceneSearcher.cs:line 64\r\n   at Examine.LuceneEngine.Providers.BaseLuceneSearcher.CreateQuery(String category, BooleanOperation defaultOperation) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\BaseLuceneSearcher.cs:line 49\r\n   at Umbraco.Examine.UmbracoContentIndex.PerformDeleteFromIndex(IEnumerable`1 itemIds, Action`1 onComplete) in D:\\a\\1\\s\\src\\Umbraco.Examine\\UmbracoContentIndex.cs:line 131\r\n   at Umbraco.Web.Search.ExamineComponent.DeferedDeleteIndex.Execute(ExamineComponent examineComponent, Int32 id, Boolean keepIfUnpublished) in D:\\a\\1\\s\\src\\Umbraco.Web\\Search\\ExamineComponent.cs:line 774\r\n   at Umbraco.Web.Search.ExamineComponent.DeferedActions.Execute() in D:\\a\\1\\s\\src\\Umbraco.Web\\Search\\ExamineComponent.cs:line 604\r\n   at Umbraco.Web.Search.ExamineComponent.DeferedActions.<>c.<Get>b__1_1(Boolean completed, DeferedActions actions) in D:\\a\\1\\s\\src\\Umbraco.Web\\Search\\ExamineComponent.cs:line 594\r\n   at Umbraco.Core.Scoping.ScopeContext.ScopeExit(Boolean completed) in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\ScopeContext.cs:line 26\r\n   --- End of inner exception stack trace ---\r\n   at Umbraco.Core.Scoping.ScopeContext.ScopeExit(Boolean completed) in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\ScopeContext.cs:line 38\r\n   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass85_0.<RobustExit>b__2() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 670\r\n   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 705\r\n   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 710\r\n   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 710\r\n   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException) in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 693\r\n   at Umbraco.Core.Scoping.Scope.Dispose() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 557\r\n   at Umbraco.Core.Services.Implement.MediaService.MoveToRecycleBin(IMedia media, Int32 userId) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\MediaService.cs:line 925\r\n   at Umbraco.Web.Editors.MediaController.DeleteById(Int32 id)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()\r\n---> (Inner Exception #0) System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\nFile name: 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at Lucene.Net.Store.SimpleFSDirectory.OpenInput(String name, Int32 bufferSize) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Store\\SimpleFSDirectory.cs:line 72\r\n   at Lucene.Net.Index.FieldsReader..ctor(Directory d, String segment, FieldInfos fn, Int32 readBufferSize, Int32 docStoreOffset, Int32 size) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\FieldsReader.cs:line 106\r\n   at Lucene.Net.Index.SegmentReader.CoreReaders.OpenDocStores(SegmentInfo si) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\SegmentReader.cs:line 356\r\n   at Lucene.Net.Index.IndexWriter.ReaderPool.Get(SegmentInfo info, Boolean doOpenStores, Int32 readBufferSize, Int32 termsIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 702\r\n   at Lucene.Net.Index.IndexWriter.ReaderPool.GetReadOnlyClone(SegmentInfo info, Boolean doOpenStores, Int32 termInfosIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 630\r\n   at Lucene.Net.Index.DirectoryReader..ctor(IndexWriter writer, SegmentInfos infos, Int32 termInfosIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\DirectoryReader.cs:line 204\r\n   at Lucene.Net.Index.IndexWriter.GetReader(Int32 termInfosIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 392\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.ReaderReopener.MaybeReopen() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 463\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.ReaderReopener.ScheduleReopen() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 291\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.ValidateSearcher() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 222\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.GetLuceneSearcher() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 80\r\n   at Examine.LuceneEngine.Providers.LuceneSearcher.GetSearchContext() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneSearcher.cs:line 89\r\n   at Examine.LuceneEngine.Providers.BaseLuceneSearcher.CreateQuery(String category, BooleanOperation defaultOperation, Analyzer luceneAnalyzer, LuceneSearchOptions searchOptions) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\BaseLuceneSearcher.cs:line 64\r\n   at Examine.LuceneEngine.Providers.BaseLuceneSearcher.CreateQuery(String category, BooleanOperation defaultOperation) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\BaseLuceneSearcher.cs:line 49\r\n   at Umbraco.Examine.UmbracoContentIndex.PerformDeleteFromIndex(IEnumerable`1 itemIds, Action`1 onComplete) in D:\\a\\1\\s\\src\\Umbraco.Examine\\UmbracoContentIndex.cs:line 131\r\n   at Umbraco.Web.Search.ExamineComponent.DeferedDeleteIndex.Execute(ExamineComponent examineComponent, Int32 id, Boolean keepIfUnpublished) in D:\\a\\1\\s\\src\\Umbraco.Web\\Search\\ExamineComponent.cs:line 774\r\n   at Umbraco.Web.Search.ExamineComponent.DeferedActions.Execute() in D:\\a\\1\\s\\src\\Umbraco.Web\\Search\\ExamineComponent.cs:line 604\r\n   at Umbraco.Web.Search.ExamineComponent.DeferedActions.<>c.<Get>b__1_1(Boolean completed, DeferedActions actions) in D:\\a\\1\\s\\src\\Umbraco.Web\\Search\\ExamineComponent.cs:line 594\r\n   at Umbraco.Core.Scoping.ScopeContext.ScopeExit(Boolean completed) in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\ScopeContext.cs:line 26<---\r\n","RequestUrl":"http://localhost:54252/umbraco/backoffice/UmbracoApi/Media/DeleteById?id=1121","SourceContext":"Umbraco.Web.Editors.MediaController","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR","HttpRequestNumber":75,"HttpRequestId":"02ba76a1-1a95-409a-85e5-48c5878d4778"}
{"@t":"2022-02-09T14:23:23.4323209Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:28:47.8380813Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":28,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":76,"HttpRequestId":"d758dff6-0172-4312-99ca-d0529a9c344d"}
{"@t":"2022-02-09T14:28:47.8819646Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":28,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":76,"HttpRequestId":"d758dff6-0172-4312-99ca-d0529a9c344d"}
{"@t":"2022-02-09T14:28:50.3579432Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:28:50.7076238Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":43,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:30:02.8054646Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"Astronauts","ContentId":1130,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":77,"HttpRequestId":"997b9c45-d3e3-4098-885b-4add6f19ce8f"}
{"@t":"2022-02-09T14:30:06.9370536Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":102,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:30:18.3687510Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"Satellites","ContentId":1129,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":78,"HttpRequestId":"1550c165-0aba-4e5a-bff1-e64be4c5b160"}
{"@t":"2022-02-09T14:30:20.8906895Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":102,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:30:31.0094344Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"Planets","ContentId":1128,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":79,"HttpRequestId":"2d296267-e207-47c2-9101-c5ce2dbaaff9"}
{"@t":"2022-02-09T14:30:33.5279989Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":43,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:30:44.5286349Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"Missions","ContentId":1097,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":105,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":80,"HttpRequestId":"0289dba1-a45f-49ab-9834-4c2dbf659e6b"}
{"@t":"2022-02-09T14:30:47.0344499Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":102,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:31:59.6552054Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"when was NASA founded?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":64,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":81,"HttpRequestId":"a88ab5d3-0a73-4f7a-bfa9-d3818d4c1084"}
{"@t":"2022-02-09T14:32:02.2762971Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:32:44.8353960Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"Why did NASA spend millions developing a pen that would work in space?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":32,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":82,"HttpRequestId":"b31003b2-e5dd-4baf-8778-ffebe926831d"}
{"@t":"2022-02-09T14:32:47.3513747Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":108,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
{"@t":"2022-02-09T14:33:31.2988541Z","@mt":"Document {ContentName} (id={ContentId}) has been published.","ContentName":"which mission was Buzz Aldrin a part of?","ContentId":0,"SourceContext":"Umbraco.Core.Services.Implement.ContentService","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":44,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"INFO ","HttpRequestNumber":83,"HttpRequestId":"5c84fc91-933c-43f6-8a68-ed3a1751851d"}
{"@t":"2022-02-09T14:33:34.1546571Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> System.IO.FileNotFoundException: Could not find file 'C:\\Users\\graeme.clark\\flight-to-orbit\\code\\FTO-2\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\External\\_1i.fdt'.\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":22164,"ProcessName":"iisexpress","ThreadId":108,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"CPH00237","Log4NetLevel":"ERROR"}
